# Generated by Django 5.2 on 2025-04-11 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='ItemInventario',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'categorias'},
        ),
    ]
