# Generated by Django 5.2 on 2025-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_inventoryitem_iteminventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventario',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
